name: 'Colorado Ninjutsu '
favicon: null
layout_spectrum: 0.02778
typography_spectrum: 0.5
title: Coloradoninjutsu.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b6251'
    - '#1a1825'
    - '#a9856b'
    - '#e1e1eb'
    - '#adb0bf'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
